(ns like-barn-brenner-best.proverbs
  (:require [clj-obt.core :as obt]))

;(obt/set-obt-path! "/home/ogrim/bin/The-Oslo-Bergen-Tagger/")
;(def initial-population (obt/obt-tag ordtak))


(def i (atom -1))
(declare ordtak-tagged)

(defn ordinary-proverb []
  (if (>= @i (dec (count ordtak-tagged)))
    (do (reset! i -1) (ordinary-proverb))
    (nth ordtak-tagged (swap! i inc))))

(def ordtak
  ["Bedre med trøtte armer enn tomme tarmer"
   "Den som er redd for å få vondt i armene, får vondt i tarmene"
   "Den som ikke i hete vil svette, får i kulde sulte"
   "Ingen er så brukbar som poteten"
   "Slit og møde gir klær og føde"
   "Denne uka gikk fort, i overmorgen er det alt onsdag, sa mannen"
   "Lediggang er roten til alt vondt"
   "Nye skjorter koster"
   "Arbeid tiltaler meg, jeg kan se på det i timesvis"
   "Hvorfor gjøre i morgen, det man kan gjøre i dag"
   "Kvinner ler når de vil, og gråter når de kan"
   "Nød lærer naken kvinne å spinne"
   "Uten mat og drikke duger helten ikke"
   "Bedre føre var, enn etter snar"
   "Borte bra, men hjemme best"
   "Like barn leker best"
   "Brent barn skyr ilden"
   "Det er ikke så farlig om pølsa er for lang"
   "Bedre med tørr kake enn intet å smake"
   "Det fins verre mat i verden enn raspeballer"
   "Bare bok gjør ingen klok"
   "Den lekse man lærer som ung, er aldri tung"
   "Det er bedre å komme fem minutter for sent enn å daue førti år for tidlig"
   "Det er ille å drukne på tørre landet"
   "En ulykke kommer sjelden alene"
   "Liten tue, kan velte stort lass"
   "Det er mangt stygt i havet, sa mannen, han så kjerringa svømme naken"
   "Det er ikke gull alt som glitrer"
   "Eple faller ikke langt fra stammen"
   "Det er bedre med en fugl i hånden enn ti på taket"
   "Jo flere kokker, jo mer søl"
   "Det du ikke vet, har du ikke vondt av"
   "Når katten er borte, danser musene på bordet"
   "Den som vil være med på leken, må tåle steken"
   "Den som sover synder ikke"
   "En ulykke kommer sjeldent alene"])

(def ordtak-tagged
  [[{:tags ["adj" "komp"], :lemma "god", :word "Bedre", :i 1} {:tags ["prep"], :lemma "med", :word "med", :i 2} {:tags ["adj" "fl" "pos"], :lemma "trøtt", :word "trøtte", :i 3} {:tags ["subst" "appell" "mask" "ub" "fl"], :lemma "arm", :word "armer", :i 4} {:tags ["prep"], :lemma "enn", :word "enn", :i 5} {:tags ["adj" "fl" "pos"], :lemma "tom", :word "tomme", :i 6} {:tags ["subst" "appell" "mask" "ub" "fl"], :lemma "tarm", :word "tarmer", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Den", :word "Den", :i 1} {:tags ["sbu"], :lemma "som", :word "som", :i 2} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 3} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "redd", :word "redd", :i 4} {:tags ["prep"], :lemma "for", :word "for", :i 5} {:tags ["inf-merke"], :lemma "å", :word "å", :i 6} {:tags ["verb" "inf" "tr11" "pa1" "d5" "d5/til" "rl6" "pa1/til" "rl14" "d6/til" "rl3/til" "pr7" "tr20" "tr14" "<aux1/perf_part>" "pa6" "<aux1/inf>"], :lemma "få", :word "få", :i 7} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "vond", :word "vondt", :i 8} {:tags ["prep"], :lemma "i", :word "i", :i 9} {:tags ["subst" "appell" "mask" "be" "fl"], :lemma "arm", :word "armene", :i 10} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 11} {:tags ["verb" "pres" "tr11" "pa1" "d5" "d5/til" "rl6" "pa1/til" "rl14" "d6/til" "rl3/til" "pr7" "tr20" "tr14" "<aux1/perf_part>" "pa6" "<aux1/inf>"], :lemma "få", :word "får", :i 12} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "vond", :word "vondt", :i 13} {:tags ["prep"], :lemma "i", :word "i", :i 14} {:tags ["subst" "appell" "mask" "be" "fl"], :lemma "tarm", :word "tarmene", :i 15}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Den", :word "Den", :i 1} {:tags ["sbu"], :lemma "som", :word "som", :i 2} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 3} {:tags ["prep"], :lemma "i", :word "i", :i 4} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "hete", :word "hete", :i 5} {:tags ["verb" "pres" "tr1" "tr2" "d1" "<aux1/infinitiv>"], :lemma "ville", :word "vil", :i 6} {:tags ["verb" "inf" "i2" "pa4" "tr12"], :lemma "svette", :word "svette", :i 7} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 8} {:tags ["verb" "pres" "tr11" "pa1" "d5" "d5/til" "rl6" "pa1/til" "rl14" "d6/til" "rl3/til" "pr7" "tr20" "tr14" "<aux1/perf_part>" "pa6" "<aux1/inf>"], :lemma "få", :word "får", :i 9} {:tags ["prep"], :lemma "i", :word "i", :i 10} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "kulde", :word "kulde", :i 11} {:tags ["verb" "inf" "tr1" "pa1" "rl4" "i3"], :lemma "sulte", :word "sulte", :i 12}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Ingen", :word "Ingen", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adv"], :lemma "så", :word "så", :i 3} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "brukbar", :word "brukbar", :i 4} {:tags ["sbu"], :lemma "som", :word "som", :i 5} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "potet", :word "poteten", :i 6}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Slit", :word "Slit", :i 1} {:tags ["konj"], :lemma "og", :word "og", :i 2} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "møde", :word "møde", :i 3} {:tags ["verb" "pres" "tr1" "tr11" "pa1" "rl4" "d5" "rl9" "tr2" "pa2" "d1" "pa5" "tr11/til" "d4" "pa3" "pa2/til" "rl3"], :lemma "gi", :word "gir", :i 4} {:tags ["subst" "appell" "nøyt" "ub" "fl"], :lemma "klær", :word "klær", :i 5} {:tags ["konj"], :lemma "og", :word "og", :i 6} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "føde", :word "føde", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Denne", :word "Denne", :i 1} {:tags ["subst" "appell" "fem" "be" "ent"], :lemma "uke", :word "uka", :i 2} {:tags ["verb" "pret" "tr1" "i1" "i2" "tr11" "pa1" "a3" "pa4" "pa2" "pa5" "pa2/til" "pr6" "a15"], :lemma "gå", :word "gikk", :i 3} {:tags ["adj" "pos" "<adv>"], :lemma "fort", :word "fort", :i 4} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 5} {:tags ["adv" "prep+subst" "@adv"], :lemma "i overmorgen", :word "i overmorgen", :i 6} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 7} {:tags ["pron" "nøyt" "ent" "pers" "3"], :lemma "det", :word "det", :i 8} {:tags ["pron" "nøyt" "ent" "pers" "3"], :lemma "alt", :word "alt", :i 9} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "onsdag", :word "onsdag", :i 10} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 11} {:tags ["verb" "pret" "tr1" "tr11" "pa1" "d5" "tr2" "d1" "d4" "pa3"], :lemma "si", :word "sa", :i 12} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "mann", :word "mannen", :i 13}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Lediggang", :word "Lediggang", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "rot", :word "roten", :i 3} {:tags ["prep"], :lemma "til", :word "til", :i 4} {:tags ["det" "nøyt" "ent" "kvant"], :lemma "all", :word "alt", :i 5} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "vond", :word "vondt", :i 6}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Nye", :word "Nye", :i 1} {:tags ["subst" "appell" "fem" "ub" "fl"], :lemma "skjorte", :word "skjorter", :i 2} {:tags ["verb" "pres" "tr1" "i1" "tr11" "pa3"], :lemma "koste", :word "koster", :i 3}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Arbeid", :word "Arbeid", :i 1} {:tags ["verb" "pres" "tr1" "d5"], :lemma "tiltale", :word "tiltaler", :i 2} {:tags ["pron" "ent" "pers" "hum" "akk" "1"], :lemma "jeg", :word "meg", :i 3} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 4} {:tags ["pron" "ent" "pers" "hum" "nom" "1"], :lemma "jeg", :word "jeg", :i 5} {:tags ["verb" "pres" "tr1" "tr3" "<aux1/infinitiv>"], :lemma "kunne", :word "kan", :i 6} {:tags ["verb" "inf" "tr1" "tr11" "tr2" "pa2" "pa5" "tr11/til" "tr3" "tr4"], :lemma "se", :word "se", :i 7} {:tags ["prep"], :lemma "på", :word "på", :i 8} {:tags ["pron" "nøyt" "ent" "pers" "3"], :lemma "det", :word "det", :i 9} {:tags ["prep"], :lemma "i", :word "i", :i 10} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "timesvis", :word "timesvis", :i 11}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Hvorfor", :word "Hvorfor", :i 1} {:tags ["verb" "inf" "tr1" "rl9" "pr3"], :lemma "gjøre", :word "gjøre", :i 2} {:tags ["adv" "prep+subst" "@adv"], :lemma "i morgen", :word "i morgen", :i 3} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 4} {:tags ["pron" "nøyt" "ent" "pers" "3"], :lemma "det", :word "det", :i 5} {:tags ["pron" "ent" "pers" "hum" "nom"], :lemma "man", :word "man", :i 6} {:tags ["verb" "pres" "tr1" "tr3" "<aux1/infinitiv>"], :lemma "kunne", :word "kan", :i 7} {:tags ["verb" "inf" "tr1" "rl9" "pr3"], :lemma "gjøre", :word "gjøre", :i 8} {:tags ["prep"], :lemma "i", :word "i", :i 9} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "dag", :word "dag", :i 10}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Kvinner", :word "Kvinner", :i 1} {:tags ["verb" "pres" "tr1" "i1" "tr11" "pa1" "a11"], :lemma "le", :word "ler", :i 2} {:tags ["sbu"], :lemma "når", :word "når", :i 3} {:tags ["pron" "fl" "pers" "3" "nom"], :lemma "de", :word "de", :i 4} {:tags ["verb" "pres" "tr1" "tr2" "d1" "<aux1/infinitiv>"], :lemma "ville", :word "vil", :i 5} {:tags ["<komma>"], :lemma "$,", :word ",", :i 6} {:tags ["konj" "clb"], :lemma "og", :word "og", :i 7} {:tags ["verb" "pres" "tr1" "i1" "tr11"], :lemma "gråte", :word "gråter", :i 8} {:tags ["sbu"], :lemma "når", :word "når", :i 9} {:tags ["pron" "fl" "pers" "3" "nom"], :lemma "de", :word "de", :i 10} {:tags ["verb" "pres" "tr1" "tr3" "<aux1/infinitiv>"], :lemma "kunne", :word "kan", :i 11}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Nød", :word "Nød", :i 1} {:tags ["verb" "pres" "tr1" "tr11" "pa1" "d5" "tr2" "d1" "tr3" "d3"], :lemma "lære", :word "lærer", :i 2} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "naken", :word "naken", :i 3} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "kvinne", :word "kvinne", :i 4} {:tags ["inf-merke"], :lemma "å", :word "å", :i 5} {:tags ["verb" "inf" "tr1" "i2" "tr11" "tr9"], :lemma "spinne", :word "spinne", :i 6}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Uten", :word "Uten", :i 1} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "mat", :word "mat", :i 2} {:tags ["konj"], :lemma "og", :word "og", :i 3} {:tags ["subst" "appell" "nøyt" "ubøy"], :lemma "drikke", :word "drikke", :i 4} {:tags ["verb" "pres" "i2" "tr12/til" "tr13/til"], :lemma "duge", :word "duger", :i 5} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "helt", :word "helten", :i 6} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Bedre", :word "Bedre", :i 1} {:tags ["verb" "inf" "tr1" "pa1" "rl4" "a6" "a7" "a12" "pa3" "tr12/til" "a2"], :lemma "føre", :word "føre", :i 2} {:tags ["verb" "pret" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "var", :i 3} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 4} {:tags ["prep"], :lemma "enn", :word "enn", :i 5} {:tags ["prep"], :lemma "etter", :word "etter", :i 6} {:tags ["subst" "appell" "nøyt" "ub" "ent"], :lemma "snar", :word "snar", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Borte", :word "Borte", :i 1} {:tags ["adj" "fl" "pos"], :lemma "bra", :word "bra", :i 2} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 3} {:tags ["konj"], :lemma "men", :word "men", :i 4} {:tags ["prep"], :lemma "hjemme", :word "hjemme", :i 5} {:tags ["adj" "ub" "sup"], :lemma "god", :word "best", :i 6}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Like", :word "Like", :i 1} {:tags ["subst" "appell" "nøyt" "ub" "fl"], :lemma "barn", :word "barn", :i 2} {:tags ["verb" "pres" "tr1" "i1" "tr11" "rl4" "rl9"], :lemma "leke", :word "leker", :i 3} {:tags ["adj" "ub" "sup"], :lemma "god", :word "best", :i 4}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Brent", :word "Brent", :i 1} {:tags ["subst" "appell" "nøyt" "ub" "ent"], :lemma "barn", :word "barn", :i 2} {:tags ["verb" "pres" "tr1"], :lemma "sky", :word "skyr", :i 3} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "ild", :word "ilden", :i 4}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 3} {:tags ["adv"], :lemma "så", :word "så", :i 4} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "farlig", :word "farlig", :i 5} {:tags ["sbu"], :lemma "om", :word "om", :i 6} {:tags ["subst" "appell" "fem" "be" "ent"], :lemma "pølse", :word "pølsa", :i 7} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 8} {:tags ["prep"], :lemma "for", :word "for", :i 9} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "lang", :word "lang", :i 10}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Bedre", :word "Bedre", :i 1} {:tags ["prep"], :lemma "med", :word "med", :i 2} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "tørr", :word "tørr", :i 3} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "kake", :word "kake", :i 4} {:tags ["sbu"], :lemma "enn", :word "enn", :i 5} {:tags ["det" "nøyt" "ent" "kvant"], :lemma "ingen", :word "intet", :i 6} {:tags ["inf-merke"], :lemma "å", :word "å", :i 7} {:tags ["verb" "inf" "tr1" "i2" "tr11"], :lemma "smake", :word "smake", :i 8}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "i2" "<s-verb>" "<*nes>"], :lemma "finnes", :word "fins", :i 2} {:tags ["adj" "komp"], :lemma "vond", :word "verre", :i 3} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "mat", :word "mat", :i 4} {:tags ["prep"], :lemma "i", :word "i", :i 5} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "verden", :word "verden", :i 6} {:tags ["prep"], :lemma "enn", :word "enn", :i 7} {:tags ["subst" "appell" "mask" "ub" "fl"], :lemma "raspeball", :word "raspeballer", :i 8}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Bare", :word "Bare", :i 1} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "bok", :word "bok", :i 2} {:tags ["verb" "pres" "tr1" "rl9" "pr3"], :lemma "gjøre", :word "gjør", :i 3} {:tags ["det" "mask" "ent" "kvant"], :lemma "ingen", :word "ingen", :i 4} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "klok", :word "klok", :i 5}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Den", :word "Den", :i 1} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "lekse", :word "lekse", :i 2} {:tags ["pron" "ent" "pers" "hum" "nom"], :lemma "man", :word "man", :i 3} {:tags ["verb" "pres" "tr1" "tr11" "pa1" "d5" "tr2" "d1" "tr3" "d3"], :lemma "lære", :word "lærer", :i 4} {:tags ["prep"], :lemma "som", :word "som", :i 5} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "ung", :word "ung", :i 6} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 7} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 8} {:tags ["adv"], :lemma "aldri", :word "aldri", :i 9} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "tung", :word "tung", :i 10}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adj" "komp"], :lemma "god", :word "bedre", :i 3} {:tags ["inf-merke"], :lemma "å", :word "å", :i 4} {:tags ["verb" "inf" "i1" "i2" "tr11" "a3" "pa4" "rl5" "pa5" "tr12" "a4" "rl15" "tr21" "tr22"], :lemma "komme", :word "komme", :i 5} {:tags ["det" "fl" "kvant"], :lemma "fem", :word "fem", :i 6} {:tags ["subst" "appell" "nøyt" "ub" "fl"], :lemma "minutt", :word "minutter", :i 7} {:tags ["adv"], :lemma "for", :word "for", :i 8} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "sen", :word "sent", :i 9} {:tags ["prep"], :lemma "enn", :word "enn", :i 10} {:tags ["inf-merke"], :lemma "å", :word "å", :i 11} {:tags ["verb" "inf"], :lemma "daue", :word "daue", :i 12} {:tags ["det" "fl" "kvant"], :lemma "førti", :word "førti", :i 13} {:tags ["subst" "appell" "nøyt" "ub" "fl"], :lemma "år", :word "år", :i 14} {:tags ["prep"], :lemma "for", :word "for", :i 15} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "tidlig", :word "tidlig", :i 16}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adj" "fl" "pos"], :lemma "ill", :word "ille", :i 3} {:tags ["inf-merke"], :lemma "å", :word "å", :i 4} {:tags ["verb" "inf" "tr1" "i2" "rl4"], :lemma "drukne", :word "drukne", :i 5} {:tags ["prep"], :lemma "på", :word "på", :i 6} {:tags ["adj" "be" "ent" "pos"], :lemma "tørr", :word "tørre", :i 7} {:tags ["subst" "appell" "nøyt" "be" "ent"], :lemma "land", :word "landet", :i 8}]
   [{:tags ["subst" "prop" "<*>"], :lemma "En", :word "En", :i 1} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "ulykke", :word "ulykke", :i 2} {:tags ["verb" "pres" "i1" "i2" "tr11" "a3" "pa4" "rl5" "pa5" "tr12" "a4" "rl15" "tr21" "tr22"], :lemma "komme", :word "kommer", :i 3} {:tags ["adv"], :lemma "sjelden", :word "sjelden", :i 4} {:tags ["adv"], :lemma "alene", :word "alene", :i 5}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Liten", :word "Liten", :i 1} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "tue", :word "tue", :i 2} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 3} {:tags ["verb" "pres" "tr1" "tr3" "<aux1/infinitiv>"], :lemma "kunne", :word "kan", :i 4} {:tags ["verb" "inf" "tr1" "i2" "pa4" "a6" "tr12" "a12" "rl15"], :lemma "velte", :word "velte", :i 5} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "stor", :word "stort", :i 6} {:tags ["subst" "appell" "nøyt" "ub" "ent"], :lemma "lass", :word "lass", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["ukjent"], :lemma "mangt", :word "mangt", :i 3} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "stygg", :word "stygt", :i 4} {:tags ["prep"], :lemma "i", :word "i", :i 5} {:tags ["subst" "appell" "nøyt" "be" "ent"], :lemma "hav", :word "havet", :i 6} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 7} {:tags ["verb" "pret" "tr1" "tr11" "pa1" "d5" "tr2" "d1" "d4" "pa3"], :lemma "si", :word "sa", :i 8} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "mann", :word "mannen", :i 9} {:tags ["<komma>"], :lemma "$,", :word ",", :i 10} {:tags ["pron" "mask" "ent" "pers" "hum" "3" "nom"], :lemma "han", :word "han", :i 11} {:tags ["sbu"], :lemma "så", :word "så", :i 12} {:tags ["subst" "appell" "fem" "be" "ent"], :lemma "kjerring", :word "kjerringa", :i 13} {:tags ["verb" "inf" "i1" "a3" "a5"], :lemma "svømme", :word "svømme", :i 14} {:tags ["adj" "ub" "m/f" "ent" "pos"], :lemma "naken", :word "naken", :i 15}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 3} {:tags ["subst" "appell" "nøyt" "ub" "ent"], :lemma "gull", :word "gull", :i 4} {:tags ["pron" "nøyt" "ent" "pers" "3"], :lemma "alt", :word "alt", :i 5} {:tags ["sbu"], :lemma "som", :word "som", :i 6} {:tags ["verb" "pres" "i2"], :lemma "glitre", :word "glitrer", :i 7}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Eple", :word "Eple", :i 1} {:tags ["verb" "pres" "i2" "pa4" "a12"], :lemma "falle", :word "faller", :i 2} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 3} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "lang", :word "langt", :i 4} {:tags ["prep"], :lemma "fra", :word "fra", :i 5} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "stamme", :word "stammen", :i 6}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Det", :word "Det", :i 1} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 2} {:tags ["adj" "komp"], :lemma "god", :word "bedre", :i 3} {:tags ["prep"], :lemma "med", :word "med", :i 4} {:tags ["det" "mask" "ent" "kvant"], :lemma "en", :word "en", :i 5} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "fugl", :word "fugl", :i 6} {:tags ["prep"], :lemma "i", :word "i", :i 7} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "hånd", :word "hånden", :i 8} {:tags ["prep"], :lemma "enn", :word "enn", :i 9} {:tags ["det" "fl" "kvant"], :lemma "ti", :word "ti", :i 10} {:tags ["prep"], :lemma "på", :word "på", :i 11} {:tags ["subst" "appell" "nøyt" "be" "ent" "<<<"], :lemma "tak", :word "taket", :i 12}]
   [{:tags ["adv"], :lemma "jo", :word "Jo", :i 1} {:tags ["adj" "komp"], :lemma "mange", :word "flere", :i 2} {:tags ["subst" "appell" "fem" "ub" "fl"], :lemma "kokke", :word "kokker", :i 3} {:tags ["<komma>"], :lemma "$,", :word ",", :i 4} {:tags ["adv"], :lemma "jo", :word "jo", :i 5} {:tags ["adj" "komp"], :lemma "mye", :word "mer", :i 6} {:tags ["subst" "appell" "nøyt" "ub" "ent" "<<<"], :lemma "søl", :word "søl", :i 7}]
   [{:tags ["sbu"], :lemma "når", :word "Når", :i 1} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "katt", :word "katten", :i 2} {:tags ["verb" "pres" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "er", :i 3} {:tags ["prep"], :lemma "borte", :word "borte", :i 4} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 5} {:tags ["verb" "pres" "tr1" "i1" "a3"], :lemma "danse", :word "danser", :i 6} {:tags ["subst" "appell" "mask" "be" "fl"], :lemma "muse", :word "musene", :i 7} {:tags ["prep"], :lemma "på", :word "på", :i 8} {:tags ["subst" "appell" "nøyt" "be" "ent"], :lemma "bord", :word "bordet", :i 9}]
   [{:tags ["subst" "prop" "<*>"], :lemma "Den", :word "Den", :i 1} {:tags ["sbu"], :lemma "som", :word "som", :i 2} {:tags ["verb" "pres" "tr1" "tr2" "d1" "<aux1/infinitiv>"], :lemma "ville", :word "vil", :i 3} {:tags ["verb" "inf" "a5" "pr1" "pr2" "<aux1/perf_part>"], :lemma "være", :word "være", :i 4} {:tags ["prep"], :lemma "med", :word "med", :i 5} {:tags ["prep"], :lemma "på", :word "på", :i 6} {:tags ["subst" "appell" "mask" "be" "ent"], :lemma "leke", :word "leken", :i 7} {:tags ["clb" "<komma>"], :lemma "$,", :word ",", :i 8} {:tags ["verb" "pres" "tr6" "pa4/til" "<aux1/infinitiv>"], :lemma "måtte", :word "må", :i 9} {:tags ["verb" "inf" "tr5" "tr18" "tr19"], :lemma "tåle", :word "tåle", :i 10} {:tags ["subst" "appell" "mask" "be" "ent" "<<<"], :lemma "stek", :word "steken", :i 11}]
   [{:tags ["pron" "mask" "fem" "ent" "pers" "3"], :lemma "den", :word "Den", :i 1} {:tags ["sbu"], :lemma "som", :word "som", :i 2} {:tags ["verb" "pres" "tr1" "i2" "pa1" "pa4"], :lemma "sove", :word "sover", :i 3} {:tags ["subst" "appell" "mask" "ub" "ent"], :lemma "synder", :word "synder", :i 4} {:tags ["adv"], :lemma "ikke", :word "ikke", :i 5}]
   [{:tags ["subst" "prop" "<*>"], :lemma "En", :word "En", :i 1} {:tags ["subst" "appell" "fem" "ub" "ent"], :lemma "ulykke", :word "ulykke", :i 2} {:tags ["verb" "pres" "i1" "i2" "tr11" "a3" "pa4" "rl5" "pa5" "tr12" "a4" "rl15" "tr21" "tr22"], :lemma "komme", :word "kommer", :i 3} {:tags ["adj" "nøyt" "ub" "ent" "pos"], :lemma "sjelden", :word "sjeldent", :i 4} {:tags ["adv" "<<<"], :lemma "alene", :word "alene", :i 5}]])
